-- =============================================================================================================================================
-- Imported Sales, Stores, and Features tables Structures.
-- Purpose
-- This script captures the tables that are automatically generated by SQL Server.
-- After importing the dataset this step was taken to extract a script that will be used to inspect how SSMS assigned datatypes to each column.
--
-- How this script was generated:
-- 1. Refresh the database after completing the import.
-- 2. Right-click the imported table.
-- 3. Select Script Table As > CREATE To > New Query Editor Window.
--
-- NOTE:
-- A script is extracted for each table but in this case i had to combine all queries for each table under one script.
-- =============================================================================================================================================

USE [retail_analysis]
GO

/****** Object:  Table [dbo].[sales]    Script Date: 2026/07/29 14:06:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[sales](
	[Store] [nvarchar](50) NOT NULL,
	[Dept] [nvarchar](50) NOT NULL,
	[Date] [nvarchar](50) NOT NULL,
	[Weekly_Sales] [nvarchar](50) NOT NULL,
	[IsHoliday] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO

-----------------------------------------------------------------------------------------------------------

USE [retail_analysis]
GO

/****** Object:  Table [dbo].[stores]    Script Date: 2026/07/29 14:06:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stores](
	[Store] [nvarchar](50) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
	[Size] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO

-----------------------------------------------------------------------------------------------------------

USE [retail_analysis]
GO

/****** Object:  Table [dbo].[features]    Script Date: 2026/07/29 14:07:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[features](
	[Store] [nvarchar](50) NOT NULL,
	[Date] [nvarchar](50) NOT NULL,
	[Temperature] [nvarchar](50) NOT NULL,
	[Fuel_Price] [nvarchar](50) NOT NULL,
	[MarkDown1] [nvarchar](50) NOT NULL,
	[MarkDown2] [nvarchar](50) NOT NULL,
	[MarkDown3] [nvarchar](50) NOT NULL,
	[MarkDown4] [nvarchar](50) NOT NULL,
	[MarkDown5] [nvarchar](50) NOT NULL,
	[CPI] [nvarchar](50) NULL,
	[Unemployment] [nvarchar](50) NULL,
	[IsHoliday] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO